# POSTTEST 7
**NAMA  : DUTA VIRA PRADHANA DIPA**

**NIM   : 2009106053**

Import Library

In [1]:
import tensorflow as tf

## Membuat Variabel Tensor

Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.00954322,  0.22430873, -1.0252323 , -0.38172796,  0.50279635],
       [ 1.641023  , -0.00851415,  0.00312497, -1.2649603 ,  0.38008437],
       [-0.32529703, -0.7273944 ,  0.4269173 ,  0.2741184 ,  1.8353487 ],
       [-0.2302495 ,  1.9381753 , -2.5721958 , -0.14674285, -0.4496302 ],
       [ 0.789963  ,  0.38593182, -0.6944267 ,  1.1335968 , -1.2476934 ]],
      dtype=float32)>

Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [3]:
bilangan_prima = [[2, 3, 5, 7, 11],
                [13, 17, 19, 23, 29],
                [31, 37, 41, 43, 47],
                [53, 59, 61, 67, 71],
                [73, 79, 83, 89, 97]]
prime_tensor = tf.convert_to_tensor(bilangan_prima, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## Menampilkan Dimensi

In [6]:
print("Dimensi dari tensor random\t:", random_tensor.shape)
print("Dimensi dari tensor bil. prima\t:", prime_tensor.shape)

Dimensi dari tensor random	: (5, 5)
Dimensi dari tensor bil. prima	: (5, 5)


## Perhitungan Aritmatika

### Penjumlahan tensor variabel random_tensor dengan variabel prime_tensor

In [8]:
penjumlahan = tf.add(random_tensor, prime_tensor)
print("Hasil penjumlahan tensor dari variabel random_tensor dengan prime_tensor:\n", penjumlahan.numpy())

Hasil penjumlahan tensor dari variabel random_tensor dengan prime_tensor:
 [[ 1.9904568  3.2243087  3.9747677  6.618272  11.502796 ]
 [14.641023  16.991486  19.003124  21.735039  29.380085 ]
 [30.674704  36.272606  41.426918  43.274117  48.83535  ]
 [52.76975   60.938175  58.427803  66.85326   70.55037  ]
 [73.78996   79.38593   82.30557   90.1336    95.752304 ]]


### Pengurangan tensor variabel random_tensor dengan variabel prime_tensor

In [10]:
pengurangan = tf.subtract(random_tensor, prime_tensor)
print("Hasil pengurangan tensor dari variabel random_tensor dengan prime_tensor:\n", pengurangan.numpy())

Hasil pengurangan tensor dari variabel random_tensor dengan prime_tensor:
 [[ -2.0095432  -2.7756913  -6.0252323  -7.381728  -10.497204 ]
 [-11.358977  -17.008514  -18.996876  -24.264961  -28.619915 ]
 [-31.325296  -37.727394  -40.573082  -42.725883  -45.16465  ]
 [-53.23025   -57.061825  -63.572197  -67.14674   -71.44963  ]
 [-72.21004   -78.61407   -83.69443   -87.8664    -98.247696 ]]


### Perkalian tensor variabel random_tensor dengan variabel prime_tensor

In [11]:
perkalian = tf.multiply(random_tensor, prime_tensor)
print("Hasil perkalian tensor dari variabel random_tensor dengan prime_tensor:\n", perkalian.numpy())

Hasil perkalian tensor dari variabel random_tensor dengan prime_tensor:
 [[-1.90864448e-02  6.72926188e-01 -5.12616158e+00 -2.67209578e+00
   5.53075981e+00]
 [ 2.13332996e+01 -1.44740492e-01  5.93743697e-02 -2.90940857e+01
   1.10224466e+01]
 [-1.00842075e+01 -2.69135933e+01  1.75036106e+01  1.17870913e+01
   8.62613907e+01]
 [-1.22032232e+01  1.14352341e+02 -1.56903946e+02 -9.83177090e+00
  -3.19237442e+01]
 [ 5.76673012e+01  3.04886131e+01 -5.76374168e+01  1.00890114e+02
  -1.21026260e+02]]


### Pembagian tensor variabel random_tensor dengan variabel prime_tensor

In [12]:
pembagian = tf.divide(random_tensor, prime_tensor)
print("Hasil pembagian tensor dari variabel random_tensor dengan prime_tensor:\n", pembagian.numpy())

Hasil pembagian tensor dari variabel random_tensor dengan prime_tensor:
 [[-4.7716112e-03  7.4769579e-02 -2.0504646e-01 -5.4532565e-02
   4.5708761e-02]
 [ 1.2623253e-01 -5.0083216e-04  1.6447193e-04 -5.4998275e-02
   1.3106357e-02]
 [-1.0493453e-02 -1.9659309e-02  1.0412618e-02  6.3748462e-03
   3.9049972e-02]
 [-4.3443302e-03  3.2850429e-02 -4.2167142e-02 -2.1901918e-03
  -6.3328198e-03]
 [ 1.0821411e-02  4.8852130e-03 -8.3665866e-03  1.2737042e-02
  -1.2862818e-02]]


### Logaritma tensor variabel random_tensor dengan variabel prime_tensor

In [17]:
logaritma = tf.math.log(random_tensor, prime_tensor)
print("Hasil logaritma tensor dari variabel random_tensor dengan prime_tensor:\n", logaritma.numpy())

Hasil logaritma tensor dari variabel random_tensor dengan prime_tensor:
 [[        nan -1.4947319          nan         nan -0.68757004]
 [ 0.49531984         nan -5.7683315          nan -0.96736205]
 [        nan         nan -0.85116494 -1.2941952   0.6072345 ]
 [        nan  0.661747           nan         nan         nan]
 [-0.23576918 -0.95209455         nan  0.12539555         nan]]


### Pangkat tensor variabel random_tensor dengan variabel prime_tensor

In [19]:
pangkat = tf.pow(random_tensor, prime_tensor)
print("Hasil pangkat tensor dari variabel random_tensor dengan prime_tensor:\n", pangkat.numpy())

Hasil pangkat tensor dari variabel random_tensor dengan prime_tensor:
 [[ 9.1073096e-05  1.1285961e-02 -1.1326909e+00 -1.1810759e-03
   5.1917444e-04]
 [ 6.2587964e+02 -6.4923039e-36  0.0000000e+00 -2.2272476e+02
   6.5542070e-13]
 [-7.5977140e-16 -7.6822480e-06  6.9838438e-16  6.7817485e-25
   2.4818410e+12]
 [-1.5722816e-34  9.0404595e+16 -1.0679359e+25 -0.0000000e+00
  -2.2528832e-25]
 [ 3.3519154e-08  2.1594164e-33 -7.1613166e-14  7.0277391e+04
  -2.1011875e+09]]


### Akar tensor variabel random_tensor dengan variabel prime_tensor

In [20]:
akar_random = tf.sqrt(random_tensor)
print("Hasil akar tensor dari variabel random_tensor:\n", akar_random.numpy())
akar_prime = tf.sqrt(prime_tensor)
print("\nHasil akar tensor dari variabel random_tensor:\n", akar_prime.numpy())

Hasil akar tensor dari variabel random_tensor:
 [[       nan 0.47361243        nan        nan 0.70908135]
 [1.2810242         nan 0.0559014         nan 0.61650985]
 [       nan        nan 0.6533891  0.52356315 1.3547504 ]
 [       nan 1.3921837         nan        nan        nan]
 [0.88879865 0.6212341         nan 1.064705          nan]]

Hasil akar tensor dari variabel random_tensor:
 [[1.4142135 1.7320508 2.236068  2.6457512 3.3166249]
 [3.6055512 4.1231055 4.358899  4.7958317 5.3851647]
 [5.5677643 6.0827627 6.4031243 6.5574384 6.8556547]
 [7.28011   7.6811457 7.81025   8.185352  8.426149 ]
 [8.5440035 8.888194  9.110434  9.433981  9.848858 ]]


## Nilai Maksimal dan Minimal

### Menampilkan nilai maksimal dari variabel random_tensor

In [23]:
max_col = tf.argmax(random_tensor, axis=0)
print("Nilai maksimal dari variabel random_tensor menurut kolom: ", max_col.numpy())
max_row = tf.argmax(random_tensor, axis=1)
print("Nilai maksimal dari variabel random_tensor menurut baris: ", max_row.numpy())

Nilai maksimal dari variabel random_tensor menurut kolom:  [1 3 2 4 2]
Nilai maksimal dari variabel random_tensor menurut baris:  [4 0 4 1 3]


### Menampilkan nilai minimal dari variabel random_tensor

In [24]:
min_col = tf.argmin(random_tensor, axis=0)
print("Nilai minimal dari variabel random_tensor menurut kolom: ", min_col.numpy())
min_row = tf.argmin(random_tensor, axis=1)
print("Nilai minimal dari variabel random_tensor menurut baris: ", min_row.numpy())

Nilai minimal dari variabel random_tensor menurut kolom:  [2 2 3 1 4]
Nilai minimal dari variabel random_tensor menurut baris:  [2 3 1 2 4]


## Concatenation

### Penggabungan tensor variabel random_tensor dengan prime_tensor

In [27]:
penggabungan = tf.concat([random_tensor, prime_tensor], axis=0)

print("Dimensi tensor_random sebelum concat\t:", random_tensor.shape)
print("Dimensi tensor_prime sebelum concat\t:", prime_tensor.shape)
print("Dimensi tensor_random & tensor_prime setelah concat\t:", penggabungan.shape)

Dimensi tensor_random sebelum concat	: (5, 5)
Dimensi tensor_prime sebelum concat	: (5, 5)
Dimensi tensor_random & tensor_prime setelah concat	: (10, 5)


## Sorting Descending 

### Sorting Descending berdasarkan baris dari variabel random_tensor dan prime_tensor

In [28]:
random_desc = tf.sort(random_tensor, direction="DESCENDING")
prime_desc = tf.sort(prime_tensor, direction="DESCENDING")

print("Hasil sorting descending pada variabel random_tensor:\n",random_desc.numpy(),"\n")
print("Hasil sorting descending pada variabel prime_tensor:\n",prime_desc.numpy())

Hasil sorting descending pada variabel random_tensor:
 [[ 0.50279635  0.22430873 -0.00954322 -0.38172796 -1.0252323 ]
 [ 1.641023    0.38008437  0.00312497 -0.00851415 -1.2649603 ]
 [ 1.8353487   0.4269173   0.2741184  -0.32529703 -0.7273944 ]
 [ 1.9381753  -0.14674285 -0.2302495  -0.4496302  -2.5721958 ]
 [ 1.1335968   0.789963    0.38593182 -0.6944267  -1.2476934 ]] 

Hasil sorting descending pada variabel prime_tensor:
 [[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]]
